---
linters:
    flake8:
    eslint:
        config: './eslint.config'
         fixer: true
    csslint:
           fixer: true
fixers:
    enable: true

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'